dhome_admin:
    path: /admin/
    methods: [GET]
    defaults:
        _controller: dhome.controller.vision:indexAction
        _sylius:
            template: DhomeWebBundle::admin/Vision/index.html.twig
