services:
    dhome.setting_schema.contact_parameter_schema:
        class: Dhome\Bundle\AdminBundle\SettingSchema\ContactParameterSchema
        tags:
            - {name: sylius.settings_schema, alias: contact}
