dhome_homepage:
    path: /
    defaults:
        _controller: DhomeWebBundle:Frontend:index

dhome_submenu:
    path: /sub-menu
    defaults:
        _controller: DhomeWebBundle:Frontend:submenu

dhome_project:
    path: /project
    defaults:
        _controller: DhomeWebBundle:Frontend:project

dhome_inspiration:
    path: /inspiration
    defaults:
        _controller: DhomeWebBundle:Frontend:inspiration

dhome_inspiration-show:
    path: /inspiration-show
    defaults:
        _controller: DhomeWebBundle:Frontend:inspirationShow

dhome_contact:
    path: /contact
    defaults:
        _controller: DhomeWebBundle:Frontend:contact
