dhome_homepage:
    path: /
    defaults:
        _controller: DhomeWebBundle:Frontend:index

dhome_submenu:
    path: /sub-menu
    defaults:
        _controller: DhomeWebBundle:Frontend:submenu

dhome_project:
    path: /project
    defaults:
        _controller: DhomeWebBundle:Frontend:project

dhome_vision:
    path: /vision
    defaults:
        _controller: DhomeWebBundle:Frontend:vision
