dhome_web_inspiration_index:
    path: /inspirations
    methods: [GET]
    defaults:
        _controller: dhome.controller.inspiration:indexAction
        _sylius:
            paginate: 12
            filterable: true
            sortable: true
            sorting:
                createdAt: DESC
            template: DhomeWebBundle::web/inspiration.html.twig

dhome_web_inspiration_show:
    path: /inspirations/detail/{id}-{title}
    defaults:
        _controller: dhome.controller.inspiration:showAction
        _sylius:
            template: DhomeWebBundle::web/_inspiration-show.html.twig
