dhome_homepage:
    path: /
    defaults:
        _controller: DhomeWebBundle:Frontend:index

dhome_web_inspirations:
    resource: "@DhomeWebBundle/Resources/config/routing/web/inspiration.yml"

dhome_web_projects:
    resource: "@DhomeWebBundle/Resources/config/routing/web/project.yml"

dhome_web_collections:
    resource: "@DhomeWebBundle/Resources/config/routing/web/collection.yml"

dhome_web_presses:
    resource: "@DhomeWebBundle/Resources/config/routing/web/press.yml"

dhome_web_contact:
    path: /contact-us.html
    methods: [GET]
    defaults:
        _controller: DhomeWebBundle:Frontend:contact
