dhome_web_project_all_index:
    path: /projects.html
    methods: [GET]
    defaults:
        _controller: dhome.controller.project:indexAction
        _sylius:
            paginate: 15
            filterable: true
            sortable: true
            sorting:
                createdAt: DESC
            template: DhomeWebBundle::web/project.html.twig

dhome_web_project_category_index:
    path: /projects/{categoryId}-{categoryName}.html
    methods: [GET]
    defaults:
        _controller: dhome.controller.project:indexAction
        _sylius:
            paginate: 15
            filterable: true
            sortable: true
            sorting:
                createdAt: DESC
            criteria:
                category: $categoryId
            template: DhomeWebBundle::web/project.html.twig

dhome_web_project_show:
    path: /projects/{id}/show.html
    defaults:
        _controller: dhome.controller.project:showAction
        _sylius:
            template: DhomeWebBundle::web/_project-show.html.twig

dhome_web_project_submenu:
    path: /projects/menu.html
    defaults:
        _controller: dhome.controller.project_category:indexAction
        _sylius:
            sortable: true
            sorting:
                name: ASC
            template: DhomeWebBundle::web/sub-menu/_sub-menu-pro.html.twig
