dhome_admin_inspiration:
    prefix: /inspirations
    resource: "@DhomeAdminBundle/Resources/config/routing/inspiration.yml"

dhome_admin_project_category:
    prefix: /project-categories
    resource: "@DhomeAdminBundle/Resources/config/routing/project_category.yml"

dhome_admin_project:
    prefix: /projects
    resource: "@DhomeAdminBundle/Resources/config/routing/project.yml"

dhome_admin_collection_category:
    prefix: /collection-categories
    resource: "@DhomeAdminBundle/Resources/config/routing/collection_category.yml"

dhome_admin_collection:
    prefix: /collections
    resource: "@DhomeAdminBundle/Resources/config/routing/collection.yml"

dhome_admin_press_category:
    prefix: /press-categories
    resource: "@DhomeAdminBundle/Resources/config/routing/press_category.yml"

dhome_admin_press:
    prefix: /presses
    resource: "@DhomeAdminBundle/Resources/config/routing/press.yml"

dhome_admin_contact:
    prefix: /contact
    resource: "@DhomeAdminBundle/Resources/config/routing/setting.yml"

dhome_admin_security:
    resource: "@DhomeAdminBundle/Resources/config/routing/security.yml"

dhome_admin_user:
    prefix: /wannaporn/dump/customer
    resource: "@DhomeAdminBundle/Resources/config/routing/user.yml"

dhome_admin_dashboard:
    path: /dashboard
    defaults:
        _controller: DhomeWebBundle:Backend:dashboard

dhome_admin_root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: dhome_admin_dashboard
        permanent: true
