dhome_admin_vision:
    prefix: /visions
    resource: "@DhomeAdminBundle/Resources/config/routing/vision.yml"

dhome_admin_project_category:
    prefix: /project-categories
    resource: "@DhomeAdminBundle/Resources/config/routing/project_category.yml"
