dhome_admin_presses_index:
    path: /
    methods: [GET]
    defaults:
        _controller: dhome.controller.press:indexAction
        _sylius:
            template: DhomeWebBundle::admin/Press/index.html.twig
            sortable: true
            sorting:
                id: ASC
            filterable: true

dhome_admin_presses_create:
    path: /create
    methods: [GET, POST]
    defaults:
        _controller: dhome.controller.press:createAction
        _sylius:
            template: DhomeWebBundle::admin/Press/create.html.twig
            redirect: dhome_admin_presses_index


dhome_admin_presses_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: dhome.controller.press:showAction
        _sylius:
            template: DhomeWebBundle::admin/Press/show.html.twig

dhome_admin_presses_update:
    path: /{id}/update
    methods: [GET, PUT, PATCH, POST]
    defaults:
        _controller: dhome.controller.press:updateAction
        _sylius:
            template: DhomeWebBundle::admin/Press/update.html.twig
            redirect: dhome_admin_presses_index

dhome_admin_presses_delete:
    path: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: dhome.controller.press:deleteAction
        _sylius:
            redirect: dhome_admin_presses_index
