dhome_admin_login:
    path: /login
    methods: [GET]
    defaults:
        _controller: sylius.controller.security:loginAction
        _sylius:
            template: DhomeWebBundle::admin/Security/login.html.twig

dhome_login_check:
    path: /login-check
    methods: [POST]
    defaults:
        _controller: sylius.controller.security:checkAction

dhome_admin_logout:
    path: /logout
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.security:logoutAction
