dhome_admin_users_index:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.customer:indexAction
        _sylius:
            template: DhomeWebBundle::admin/User/index.html.twig
            sortable: true
            sorting:
                id: ASC
            filterable: true

dhome_admin_users_create:
    path: /create
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.customer:createAction
        _sylius:
            template: DhomeWebBundle::admin/User/create.html.twig
            redirect: dhome_admin_users_index

dhome_admin_users_update:
    path: /{id}/update
    methods: [GET, PUT, PATCH, POST]
    defaults:
        _controller: sylius.controller.customer:updateAction
        _sylius:
            template: DhomeWebBundle::admin/User/update.html.twig
            redirect: dhome_admin_users_index

dhome_admin_users_delete:
    path: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.customer:deleteAction
        _sylius:
            redirect: dhome_admin_users_index
