dhome_admin_visions:
    path: /visions
    methods: [GET]
    defaults:
        _controller: dhome.controller.vision:indexAction
        _sylius:
            template: DhomeWebBundle::admin/Vision/index.html.twig
            sortable: true
            filterable: true
