dhome_admin_visions_index:
    path: /
    methods: [GET]
    defaults:
        _controller: dhome.controller.vision:indexAction
        _sylius:
            template: DhomeWebBundle::admin/Vision/index.html.twig
            sortable: true
            sorting:
                id: ASC
            filterable: true

dhome_admin_visions_create:
    path: /create
    methods: [GET, POST]
    defaults:
        _controller: dhome.controller.vision:createAction
        _sylius:
            template: DhomeWebBundle::admin/Vision/create.html.twig
            redirect: dhome_admin_visions_index


dhome_admin_visions_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: dhome.controller.vision:showAction
        _sylius:
            template: DhomeWebBundle::admin/Vision/show.html.twig

dhome_admin_visions_update:
    path: /{id}/update
    methods: [GET, PUT, PATCH, POST]
    defaults:
        _controller: dhome.controller.vision:updateAction
        _sylius:
            template: DhomeWebBundle::admin/Vision/update.html.twig
            redirect: dhome_admin_visions_index

dhome_admin_visions_delete:
    path: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: dhome.controller.vision:deleteAction
        _sylius:
            redirect: dhome_admin_visions_index
