# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
#    providers:
#        in_memory:
#            memory: ~

    providers:
        sylius_user_provider:
            id: sylius.user_provider.name_or_email

    encoders:
            Symfony\Component\Security\Core\User\UserInterface: sha512

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
#
#        main:
#            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

#ROLE_ALLOWED_TO_SWITCH
        admin:
            switch_user: true
            context: user
            pattern: /admin.*
            form_login:
                provider: sylius_user_provider
                login_path: /admin/login
                check_path: /admin/login-check
                failure_path: /admin/login
                default_target_path: /admin
                use_forward: false
                use_referer: true
            logout:
                path: /admin/logout
                target: /admin/

            anonymous: true
            remember_me:
                key: %secret%
                name: DHOME_REMEMBER_ME
                lifetime: 31536000
                always_remember_me: true
                remember_me_parameter: _remember_me

#        oauth_token:
#                pattern:  ^/oauth/v2/token
#                security: false
#
#            oauth_authorize:
#                pattern:  ^/oauth/v2/auth
#                security: false

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "/admin.*", role: ROLE_ADMIN }

        - { path: "/_partial.*", ip: 127.0.0.1 }
