Dhome\Bundle\AdminBundle\Model\Inspiration:
    type: entity
    table: dhome_inspiration

    gedmo:
        loggable: true

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        title:
            type: string
            length: 100

        subTitle:
            type: string
            length: 255
            column: sub_title

        content:
            type: text

        videoLink:
            type: string
            column: video_link
            nullable: true

        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create

        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update

    manyToOne:
        user:
            targetEntity: Sylius\Component\User\Model\User
            nullable: true

        image:
            targetEntity: Dhome\Bundle\MediaBundle\Model\InspirationImage
            nullable: true
            cascade: ["persist"]
            joinColumn:
                nullable: true
                onDelete: "CASCADE"
                image_id:
                    referencedColumnName: id
