Dhome\Bundle\AdminBundle\Model\Press:
    type: entity
    table: dhome_press

    gedmo:
        loggable: true

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            length: 100

        shortDescription:
            type: string
            length: 255
            column: short_description

        content:
            type: text

        videoLink:
            type: string
            column: video_link
            nullable: true

        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create

        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update

    oneToMany:
        images:
            targetEntity: Dhome\Bundle\MediaBundle\Model\PressImage
            cascade: [all]
            mappedBy: press
            orphanRemoval: true

    manyToOne:
        category:
            targetEntity: Dhome\Bundle\AdminBundle\Model\PressCategory
            inversedBy: presses
            joinColumn:
                nullable: false
                onDelete: "CASCADE"
                category_id:
                    referencedColumnName: id

        user:
            targetEntity: Sylius\Component\User\Model\User
            nullable: true
