Dhome\Bundle\AdminBundle\Model\ProjectCategory:
    type: entity
    table: dhome_project_category

    gedmo:
        loggable: true

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            length: 50

        icon:
            type: string
            length: 20
            nullable: true

    oneToMany:
        projects:
            targetEntity: Dhome\Bundle\AdminBundle\Model\Project
            mappedBy: category
            cascade: [all]
            orphanRemoval: true

    lifecycleCallbacks: {  }
