Dhome\Bundle\AdminBundle\Model\Vision:
    type: entity
    table: dhome_vision

    gedmo:
        loggable: true

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        title:
            type: string
            length: 100

        subTitle:
            type: string
            length: 255
            column: sub_title
            nullable: true

        content:
            type: text

        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create

        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update

    manyToOne:
        user:
            targetEntity: Sylius\Component\User\Model\User
            nullable: false
