Dhome\Bundle\MediaBundle\Model\CollectionImage:
    type: entity
    table: dhome_collection_image

    gedmo:
        loggable: true

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        title:
            type: string
            length: 100

        position:
            type: integer

        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create

        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update

    manyToOne:
        image:
            targetEntity: Dhome\Bundle\MediaBundle\Model\Image
            cascade: [all]
            joinColumn:
                nullable: true
                onDelete: "CASCADE"
                image_id:
                    referencedColumnName: id

        collection:
            targetEntity: Dhome\Bundle\AdminBundle\Model\ProductCollection
            inversedBy: images
