Dhome\Bundle\MediaBundle\Model\CollectionImage:
    type: entity
    table: dhome_collection_image

    gedmo:
        loggable: true

    fields:
        title:
            type: string
            length: 100
            nullable: true

        position:
            type: integer
            nullable: true

    manyToOne:
        collection:
            targetEntity: Dhome\Bundle\AdminBundle\Model\ProductCollection
            inversedBy: images
