Dhome\Bundle\MediaBundle\Model\PressImage:
    type: entity
    table: dhome_press_image

    gedmo:
        loggable: true

    fields:
        title:
            type: string
            length: 100
            nullable: true

        position:
            type: integer
            nullable: true

    manyToOne:
        press:
            targetEntity: Dhome\Bundle\AdminBundle\Model\Press
            inversedBy: images
