Dhome\Bundle\MediaBundle\Model\ProjectImage:
    type: entity
    table: dhome_project_image

    gedmo:
        loggable: true

    fields:
        title:
            type: string
            length: 100
            nullable: true

        position:
            type: integer
            nullable: true

    manyToOne:
        project:
            targetEntity: Dhome\Bundle\AdminBundle\Model\Project
            inversedBy: images
