Dhome\Bundle\MediaBundle\Model\VisionImage:
    type: entity
    table: dhome_vision_image

    gedmo:
        loggable: true

    fields:
        title:
            type: string
            length: 100
            nullable: true

        position:
            type: integer
            nullable: true

    manyToOne:
        vision:
            targetEntity: Dhome\Bundle\AdminBundle\Model\Vision
            inversedBy: images
