Dhome\Bundle\MediaBundle\Model\VisionImage:
    type: entity
    table: dhome_vision_image

    attributeOverride:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    gedmo:
        loggable: true

    fields:
        title:
            type: string
            length: 100
            nullable: true

        position:
            type: integer
            nullable: true
